engines:
  golint:
    enabled: true
  govet:
    enabled: true
  gofmt:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - go
ratings:
  paths:
  - "**.go"
exclude_paths:
- "**/vendor/**/*"
